// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"time"
)

type Contract struct {
	ID        string     `json:"id" dynamodbav:"id"`
	Template  string    `json:"template" dynamodbav:"template"`
	CreatedAt time.Time `json:"createdAt" dynamodbav:"createdAt"`
}

type Party struct {
	Username   string    `json:"username"`
	Role       string    `json:"role"`
	ContractID int64     `json:"contractID"`
	CreatedAt  time.Time `json:"createdAt"`
}

type Session struct {
	ID           string `json:"id"  dynamodbav:"id"`
	Username     string    `json:"username" dynamodbav:"username"`
	RefreshToken string    `json:"refreshToken" dynamodbav:"refreshToken"`
	UserAgent    string    `json:"userAgent" dynamodbav:"userAgent"`
	ClientIp     string    `json:"clientIp" dynamodbav:"clientIp"`
	IsBlocked    bool      `json:"isBlocked" dynamodbav:"isBlocked"`
	ExpiresAt    time.Time `json:"expiresAt" dynamodbav:"expiresAt"`
	CreatedAt    time.Time `json:"createdAt" dynamodbav:"createdAt"`
}

type Signature struct {
	Username   string    `json:"username"`
	ContractID int64     `json:"contractID"`
	CreatedAt  time.Time `json:"createdAt"`
}

type User struct {
	FirstName      string    `json:"firstName" dynamodbav:"firstName"`
	LastName       string    `json:"lastName" dynamodbav:"lastName"`
	Username       string    `json:"username" dynamodbav:"username"`
	Email          string    `json:"email" dynamodbav:"email"`
	PasswordHashed string    `json:"passwordHashed" dynamodbav:"passwordHashed"`
	ChangedAt      time.Time `json:"changedAt" dynamodbav:"changedAt"`
	CreatedAt      time.Time `json:"createdAt" dynamodbav:"createdAt"`
}
