// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Contract struct {
	ID        int64     `json:"id"`
	Template  string    `json:"template"`
	CreatedAt time.Time `json:"createdAt"`
}

type Party struct {
	Username   string    `json:"username"`
	Role       string    `json:"role"`
	ContractID int64     `json:"contractID"`
	CreatedAt  time.Time `json:"createdAt"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	RefreshToken string    `json:"refreshToken"`
	UserAgent    string    `json:"userAgent"`
	ClientIp     string    `json:"clientIp"`
	IsBlocked    bool      `json:"isBlocked"`
	ExpiresAt    time.Time `json:"expiresAt"`
	CreatedAt    time.Time `json:"createdAt"`
}

type Signature struct {
	Username   string    `json:"username"`
	ContractID int64     `json:"contractID"`
	CreatedAt  time.Time `json:"createdAt"`
}

type User struct {
	FirstName      string    `json:"firstName"`
	LastName       string    `json:"lastName"`
	Username       string    `json:"username"`
	Email          string    `json:"email"`
	PasswordHashed string    `json:"passwordHashed"`
	ChangedAt      time.Time `json:"changedAt"`
	CreatedAt      time.Time `json:"createdAt"`
}
